    package studentsystem;

    import java.awt.Color;
    import java.awt.Font;
    import java.util.ArrayList;
    import java.util.List;
    import javax.swing.JLabel;
    import javax.swing.JPanel;
    import javax.swing.JOptionPane;
    import javax.swing.UIManager;
    import javax.swing.plaf.FontUIResource;
    import javax.swing.table.DefaultTableCellRenderer;
    import javax.swing.table.DefaultTableModel;

    public final class SFStudent extends javax.swing.JFrame {

    List<Student> list = new ArrayList<>();
    static int pos = 0;
    Student x;
    static int check=0;
    JPanel panel;

    public SFStudent() {
        initComponents();
        this.jPanel1.setBackground(Color.LIGHT_GRAY);

        System.out.println("Danh sách khởi tạo: " + list.size()); // Kiểm tra số lượng phần tử trong danh sách

        ViewTable("");  // Bảng trống khi khởi động
    }

    public void View()
    {
    x = list.get(pos);
    this.txtID.setText(x.getID());
    this.txtName.setText(x.getName());
    this.txtAge.setText(""+x.getAge());
    OnOff(true, false);
    }
    @SuppressWarnings("deprecation")
    public void OnOff(boolean a, boolean b)
    {
    this.btnSave.show(b);
    this.btnCancel.show(b);
    //----------------
    this.btnAdd.show(a);
    this.btnEdit.show(a);
    this.btnDelete.show(a);
    }
    public void ViewTable(String name) {
        // Lấy model của bảng
        DefaultTableModel model = (DefaultTableModel) this.tblStudent.getModel();
        model.setNumRows(0);  // Xóa hết các dòng hiện tại trong bảng

        // Thêm từng sinh viên từ danh sách vào bảng
        int n = 1;
        for (Student x : list) {
            model.addRow(new Object[]{n++, x.getID(), x.getName(), x.getAge()});
        }

        // Thiết lập giao diện bảng
        this.tblStudent.setRowHeight(22);
        this.tblStudent.getColumnModel().getColumn(0).setWidth(10);
        this.tblStudent.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.tblStudent.getColumnModel().getColumn(2).setPreferredWidth(250);
        this.tblStudent.getColumnModel().getColumn(3).setPreferredWidth(100);
    }

    public List<Student> SearchByName(String name) {
        List<Student> matchingStudents = new ArrayList<>();
        for (Student student : list) {
            if (student.getName().equalsIgnoreCase(name)) {
                matchingStudents.add(student);  // Thêm sinh viên vào danh sách nếu tên trùng
            }
        }
        return matchingStudents;
    }


    public Student Search(String s)
    {
    for (Student x:list)
    {
    if (x.getID().equals(s))
    return x;
    }
    return x;
    }
    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    txtID = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtAge = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    btnAdd = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnSave = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblStudent = new javax.swing.JTable();
    jLabel5 = new javax.swing.JLabel();
    txtSearchName = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("CHương trình quản lý sinh viên");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ SINH VIÊN");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
    .addContainerGap(192, Short.MAX_VALUE)
    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(135, 135, 135))
    );
    jPanel1Layout.setVerticalGroup(
    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
    .addContainerGap(43, Short.MAX_VALUE)
    .addComponent(jLabel1)
    .addGap(41, 41, 41))
    );

    txtID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    txtID.addActionListener(this::txtIDActionPerformed);

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel2.setText("Mã sinh viên");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel3.setText("Tuổi sinh viên");

    txtAge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

    txtName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    txtName.addActionListener(this::txtNameActionPerformed);

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel4.setText("Họ tên sinh viên");

    btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnAdd.setText("Thêm");
    btnAdd.addActionListener(this::btnAddActionPerformed);

    btnEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnEdit.setText("Sửa");
    btnEdit.addActionListener(this::btnEditActionPerformed);

    btnDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnDelete.setText("Xóa");
    btnDelete.addActionListener(this::btnDeleteActionPerformed);

    btnSave.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnSave.setText("Lưu");
    btnSave.addActionListener(this::btnSaveActionPerformed);

    btnCancel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    btnCancel.setText("Hủy bỏ");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnCancelActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(7, 7, 7)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(28, 28, 28)
    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(28, 28, 28)
    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addGap(34, 34, 34)
    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addContainerGap(9, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(45, 45, 45)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(jLabel2)
    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(14, 14, 14)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(jLabel4)
    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(18, 18, 18)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(jLabel3))
    .addGap(37, 37, 37)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(btnAdd)
    .addComponent(btnEdit)
    .addComponent(btnDelete))
    .addGap(27, 27, 27)
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(btnSave)
    .addComponent(btnCancel))
    .addContainerGap(54, Short.MAX_VALUE))
    );

    tblStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    tblStudent.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
    "No.", "ID", "Name", "Age"
    }
    ));
    tblStudent.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
    tblStudentFocusGained(evt);
    }
    });
    tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
    tblStudentMouseClicked(evt);
    }
    });
    tblStudent.addPropertyChangeListener((java.beans.PropertyChangeEvent evt) -> {
    tblStudentPropertyChange(evt);
    });
    tblStudent.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyPressed(java.awt.event.KeyEvent evt) {
    tblStudentKeyPressed(evt);
    }
    public void keyReleased(java.awt.event.KeyEvent evt) {
    tblStudentKeyReleased(evt);
    }
    });
    tblStudent.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
    public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
    tblStudentVetoableChange(evt);
    }
    });
    jScrollPane1.setViewportView(tblStudent);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel5.setText("Tìm kiếm tên sv:");

    txtSearchName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    btnSearch.setText("Tìm");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnSearchActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel3Layout.createSequentialGroup()
    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
    .addGroup(jPanel3Layout.createSequentialGroup()
    .addGap(38, 38, 38)
    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(0, 12, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel3Layout.createSequentialGroup()
    .addGap(15, 15, 15)
    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    .addComponent(jLabel5)
    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addComponent(btnSearch))
    .addGap(18, 18, 18)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addGroup(layout.createSequentialGroup()
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        // Lấy dữ liệu từ các trường nhập liệu
        String id = txtID.getText();
        String name = txtName.getText();
        int age;

        try {
            age = Integer.parseInt(txtAge.getText());  // Chuyển đổi tuổi sang kiểu số
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tuổi phải là số nguyên hợp lệ!");
            return;
        }

        // Kiểm tra nếu các trường nhập liệu không trống
        if (id.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ mã sinh viên và tên!");
            return;
        }

        // Tạo một đối tượng Student mới
        Student newStudent = new Student(id, name, age);

        // Thêm sinh viên vào danh sách
        list.add(newStudent);

        // Cập nhật bảng với dữ liệu mới
        ViewTable("");  // Cập nhật để hiển thị sinh viên vừa thêm

        // Xóa các trường nhập liệu sau khi thêm
        txtID.setText("");
        txtName.setText("");
        txtAge.setText("");
    }


    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    check = -1;
    OnOff(false, true);
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Arial", Font.BOLD, 20)));

        Object[] options = {"Xóa một sinh viên", "Xóa tất cả sinh viên", "Hủy"};
        int choice = JOptionPane.showOptionDialog(panel, 
                        "Bạn muốn xóa một sinh viên hay tất cả sinh viên?", 
                        "Xóa sinh viên", 
                        JOptionPane.YES_NO_CANCEL_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, 
                        null, options, options[0]);

        if (choice == 0) {  // Xóa một sinh viên
            int n = JOptionPane.showConfirmDialog(panel, "Bạn có chắc chắn muốn xóa sinh viên này không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);

            if (n == JOptionPane.YES_OPTION) {
                list.remove(pos);
                pos = Math.max(0, Math.min(pos, list.size() - 1)); // Cập nhật pos
                View();
                ViewTable(this.txtSearchName.getText());
            }
        } else if (choice == 1) {  // Xóa tất cả sinh viên
            int n = JOptionPane.showConfirmDialog(panel, "Bạn có chắc chắn muốn xóa tất cả sinh viên không?", "Cảnh báo", JOptionPane.YES_NO_OPTION);

            if (n == JOptionPane.YES_OPTION) {
                list.clear();
                pos = 0;
                ViewTable("");  // Làm sạch bảng
                JOptionPane.showMessageDialog(panel, "Tất cả sinh viên đã bị xóa.");
            }
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // Lấy thông tin từ các ô nhập liệu
        String id = txtID.getText().trim();
        String name = txtName.getText().trim();
        String ageStr = txtAge.getText().trim();

        // Kiểm tra thông tin đầu vào
        if (id.isEmpty() || name.isEmpty() || ageStr.isEmpty()) {
            JOptionPane.showMessageDialog(panel, "Vui lòng nhập đầy đủ thông tin sinh viên.");
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageStr);
            if (age < 0) {
                JOptionPane.showMessageDialog(panel, "Tuổi không thể âm.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(panel, "Vui lòng nhập tuổi hợp lệ.");
            return;
        }

        // Tạo đối tượng Student mới
        Student student = new Student(id, name, age);

        // Thêm hoặc cập nhật sinh viên trong danh sách
        if (pos >= 0 && pos < list.size()) {
            // Cập nhật sinh viên nếu pos hợp lệ
            list.set(pos, student);
            JOptionPane.showMessageDialog(panel, "Thông tin sinh viên đã được cập nhật.");
        } else {
            // Thêm sinh viên mới vào danh sách
            list.add(student);
            JOptionPane.showMessageDialog(panel, "Sinh viên đã được thêm vào danh sách.");
        }

        // Cập nhật bảng hiển thị
        View();
        ViewTable("");  // Cập nhật bảng sau khi lưu
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelActionPerformed(evt);
        }
    });

        System.out.println("Nút Hủy bỏ đã được nhấn."); // Debugging

        // Đặt lại các trường nhập liệu
        txtID.setText("");     
        txtName.setText("");   
        txtAge.setText("");    

        // Chuyển về giao diện chính (đảm bảo giao diện chính đã khởi tạo đúng)
        showMainInterface();
    }


    private void showMainInterface() {
        System.out.println("Hiển thị giao diện chính."); // Debugging

        // Ẩn giao diện hiện tại
        this.setVisible(false);

        // Kiểm tra khởi tạo MainFrame đúng cách
        MainFrame mainFrame = new MainFrame();  
        mainFrame.setVisible(true);  // Hiện giao diện chính
    }


    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {
    // TODO add your handling code here:
    //pos = this.tblStudent.getSelectedRow();
    int row = this.tblStudent.getSelectedRow();
    int col = 1;
    String s = this.tblStudent.getModel().getValueAt(row,col).toString();
    pos = list.indexOf(Search(s));
    View();
    }

    private void tblStudentPropertyChange(java.beans.PropertyChangeEvent evt) {
    // TODO add your handling code here:

    }

    private void tblStudentFocusGained(java.awt.event.FocusEvent evt) {
    // TODO add your handling code here:

    }

    private void tblStudentVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
    // TODO add your handling code here:

    }

    private void tblStudentKeyPressed(java.awt.event.KeyEvent evt) {
    // TODO add your handling code here:
    }

    private void tblStudentKeyReleased(java.awt.event.KeyEvent evt) {
    // TODO add your handling code here:
    //pos = this.tblStudent.getSelectedRow();
    int row = this.tblStudent.getSelectedRow();
    int col = 1;
    String s = this.tblStudent.getModel().getValueAt(row,col).toString();
    pos = list.indexOf(Search(s));
    View();
    }

   private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
    // Xử lý sự kiện khi người dùng nhấn nút tìm kiếm theo tên
    String name = txtSearchName.getText().trim();  // Lấy tên từ ô nhập liệu

    // Gọi hàm tìm kiếm theo tên và trả về danh sách các sinh viên có tên trùng nhau
    List<Student> results = SearchByName(name);

    // Cập nhật bảng hiển thị kết quả tìm kiếm
    DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
    model.setRowCount(0);  // Xóa tất cả các hàng hiện tại trong bảng

    // Kiểm tra kết quả tìm kiếm
    if (results != null && !results.isEmpty()) {
        // Thêm tất cả sinh viên tìm thấy vào bảng
        for (int i = 0; i < results.size(); i++) {
            Student student = results.get(i);
            model.addRow(new Object[]{i + 1, student.getID(), student.getName(), student.getAge()});
        }
    } else {
        // Nếu không tìm thấy sinh viên nào, hiển thị thông báo một lần
        boolean notificationDisplayed = false; // Biến kiểm tra trạng thái thông báo
        if (!notificationDisplayed) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên có tên: " + name);
            notificationDisplayed = true; // Cập nhật trạng thái thông báo
        }
    }
}


    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    }

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    */
    try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    break;
    }
    }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(SFStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
    new SFStudent().setVisible(true);
    }
    });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearchName;

    // End of variables declaration

    public List<Student> getList() {
    return list;
    }
    }
